baseURL = "https://blog.183112.xyz"
languageCode = "en-us"
title = "孤岛"
theme = "PaperMod"

[params]
    defaultTheme = "auto"
    showReadingTime = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowFullTextContent = false

    [assets]
        favicon = "images/debian-logo.svg"

    [params.label]
        text = "孤岛"
        icon = "images/debian-logo.svg"
        iconHeight = 35

    [params.homeInfoParams]
        Title = "Welcome To My World"
        Content = "Music, Movies, Musings"

[[menu.main]]
    name = "Archive"
    url = "/archives"
    weight = 10
[[menu.main]]
    name = "Search"
    url = "/search"
    weight = 20
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 30

[outputs]
    home = ["HTML", "RSS", "JSON"]
